export const ACTIONS = {
    CREATE: 'create',
    EDIT: 'edit',
    DELETE: 'delete',
    VIEW: 'view',
    DATABASE_ACTIONS: 'database_actions',
    DISABLE: 'disable',
    FEATURE: 'feature',
    TOGGLE_VISIBILITY: 'toggle_visibility',
    VIEW_HISTORY: 'view_history',
    UPLOAD: 'upload',
    DOWNLOAD: 'download',
    PUBLISH: 'publish',
    ARCHIVE: 'archive',
    RESTORE: 'restore',
    IMPORT: 'import',
    EXPORT: 'export',
    APPROVE: 'approve',
    EXECUTE: 'execute',
    CONFIGURE: 'configure',
    MANAGE: 'manage',
    VIEW_AUDIT_LOGS: 'view_audit_logs'
};
